#!/usr/bin/env python3
"""Genera data/talks/*.json e index.json desde las definiciones de este archivo.
Añadir una conversación = añadir un bloque TALK(...) y ejecutar: python3 tools/build_talks.py"""
import json, os, re
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "talks")
TALKS = []
def T(en, es): return {"t": en, "es": es}
def Y(say, es, keys, alts=(), hint=""): return {"y": {"say": say, "es": es, "keys": keys, "alts": list(alts), "hint": hint}}
def C(q, opts, a, es=""): return {"c": {"q": q, "o": opts, "a": a, "es": es}}
def TALK(id, title, es, level, track, topic, goal, phrases, turns, dev=None, minutes=8):
    TALKS.append(dict(id=id, title=title, es=es, level=level, track=track, topic=topic, goal=goal, minutes=minutes, phrases=phrases, turns=turns, **({"dev": dev} if dev else {})))

TALK("neighbour", "Meeting a new neighbour", "Presentarte y conversar con un vecino nuevo", "B1.1", "daily", "Vida diaria",
 "Presentarte, hablar de dónde vives, de tu rutina y hacer planes sencillos.",
 [["Nice to meet you.", "Mucho gusto."], ["I've just moved in.", "Acabo de mudarme."], ["How long have you lived here?", "¿Cuánto tiempo llevas viviendo aquí?"], ["It's a bit noisy, but I'm used to it.", "Es algo ruidoso, pero estoy acostumbrado."], ["We should grab a coffee sometime.", "Deberíamos tomar un café algún día."]],
 [T("Oh, hi! You must be the new neighbour. I'm Sarah, I live in the flat next door. Welcome to the building!", "¡Hola! Debes ser el vecino nuevo. Soy Sarah, vivo en el piso de al lado. ¡Bienvenido al edificio!"),
  Y("Hi Sarah, nice to meet you. I'm Luis, I've just moved in last week.", "Hola Sarah, mucho gusto. Soy Luis, me mudé la semana pasada.", [["nice to meet you", "pleased to meet you", "good to meet you"], ["luis", "moved", "moved in"]], ["Nice to meet you Sarah. My name is Luis and I moved here last week."], "Nice to meet you..."),
  T("Great! So, where are you from originally? I can hear a bit of an accent, and I love it.", "¡Genial! ¿De dónde eres originalmente? Noto un poco de acento y me encanta."),
  Y("I'm from Venezuela, but I've been living abroad for a few years now.", "Soy de Venezuela, pero llevo unos años viviendo fuera.", [["venezuela", "from"], ["years", "abroad", "living"]], ["I come from Venezuela and I have lived abroad for some years."], "I'm from..."),
  T("That's interesting. Honestly, the neighbourhood is great, but the walls are quite thin, so you might hear the neighbours upstairs. They're nice, though. They have a dog called Max who barks at the postman every morning.", "Qué interesante. Sinceramente, el barrio es genial pero las paredes son finas, y quizás oigas a los vecinos de arriba. Son amables. Tienen un perro, Max, que le ladra al cartero cada mañana."),
  C("What does Sarah warn him about?", ["The rent is expensive", "The walls are thin and a dog barks", "The building has no elevator"], 1, "¿De qué le advierte Sarah?"),
  Y("Don't worry, I'm used to noise. I actually work from home, so I'll get to meet Max.", "No te preocupes, estoy acostumbrado al ruido. Trabajo desde casa, así que conoceré a Max.", [["used to", "don't worry", "no problem"], ["work", "home"]], ["It's fine, I don't mind the noise. I work from home so I will meet Max."], "I work from home..."),
  T("Oh, what do you do? I'm a nurse, so my schedule is all over the place. Sometimes I work nights and sleep all day.", "¿A qué te dedicas? Yo soy enfermera, así que mi horario es un caos. A veces trabajo de noche y duermo de día."),
  Y("I'm a software developer. I write code for a small company and I work remotely.", "Soy desarrollador de software. Escribo código para una empresa pequeña y trabajo a distancia.", [["software", "developer", "programmer"], ["work", "remotely", "company", "code"]], ["I work as a programmer for a small company from home."], "I'm a software developer..."),
  T("Nice! Listen, there's a small supermarket two streets down, and the bakery on the corner is fantastic. If you ever need anything, just knock. Oh, and we're having a small barbecue on the roof on Saturday. You should come!", "¡Genial! Mira, hay un supermercado pequeño a dos calles, y la panadería de la esquina es fantástica. Si necesitas algo, toca la puerta. Y el sábado hacemos una barbacoa en la azotea. ¡Deberías venir!"),
  C("What is happening on Saturday?", ["A building meeting", "A barbecue on the roof", "A dinner at the bakery"], 1, "¿Qué pasa el sábado?"),
  Y("That sounds great, I'd love to come. Can I bring something to drink?", "Suena genial, me encantaría ir. ¿Puedo llevar algo de beber?", [["love to", "would like", "sounds great", "sounds good"], ["bring", "drink"]], ["Sounds good, I would love to come. Should I bring a drink?"], "I'd love to come..."),
  T("Perfect! Just bring yourself, but some juice is always welcome. It starts at six. See you then, Luis!", "¡Perfecto! Tráete a ti mismo, pero un jugo siempre viene bien. Empieza a las seis. ¡Nos vemos, Luis!"),
  Y("Thanks, Sarah. See you on Saturday at six. Have a nice day!", "Gracias, Sarah. Nos vemos el sábado a las seis. ¡Que tengas buen día!", [["thanks", "thank you"], ["saturday", "six", "see you"]], ["Thank you Sarah, see you Saturday at six. Have a good day."], "See you on Saturday...")])

TALK("doctor", "At the doctor's", "Describir síntomas y entender indicaciones médicas", "B1.1", "daily", "Salud",
 "Explicar cómo te sientes, desde cuándo, y entender recomendaciones.",
 [["I've had a headache since Monday.", "Tengo dolor de cabeza desde el lunes."], ["It hurts here.", "Me duele aquí."], ["I'm allergic to penicillin.", "Soy alérgico a la penicilina."], ["How often should I take it?", "¿Cada cuánto debo tomarlo?"], ["Get plenty of rest.", "Descansa mucho."]],
 [T("Good morning, please take a seat. So, what seems to be the problem today?", "Buenos días, siéntese. ¿Cuál parece ser el problema hoy?"),
  Y("I've had a sore throat and a cough since Monday, and I feel very tired.", "Tengo dolor de garganta y tos desde el lunes y me siento muy cansado.", [["sore throat", "throat"], ["cough"], ["since monday", "monday", "days"]], ["My throat hurts and I have had a cough since Monday. I am very tired."], "I've had a sore throat..."),
  T("I see. Have you had a fever, or any trouble breathing? Also, are you taking any medication at the moment?", "Entiendo. ¿Ha tenido fiebre o problemas para respirar? ¿Toma algún medicamento ahora?"),
  Y("No fever, and I can breathe normally. I'm not taking any medication, but I'm allergic to penicillin.", "Sin fiebre y respiro normal. No tomo medicación, pero soy alérgico a la penicilina.", [["no fever", "fever"], ["allergic", "penicillin"], ["not taking", "no medication", "medication"]], ["I don't have a fever and I breathe fine. I don't take medicine. I have an allergy to penicillin."], "I'm allergic to..."),
  C("What is important the patient tells the doctor?", ["He has no fever", "He is allergic to penicillin", "He takes vitamins"], 1, "¿Qué dato importante dice el paciente?"),
  T("Thank you, that's very useful. It looks like a viral infection, so antibiotics won't help. I'll give you something for the throat. Take one tablet three times a day, after meals, for five days. Drink plenty of water and get as much rest as you can.", "Gracias, es muy útil. Parece una infección viral, así que los antibióticos no ayudarían. Le daré algo para la garganta. Una pastilla tres veces al día, después de comer, durante cinco días. Beba mucha agua y descanse."),
  C("How often should he take the tablet?", ["Once a day", "Three times a day", "Only at night"], 1, "¿Cada cuánto debe tomarla?"),
  Y("So I should take one tablet three times a day after meals, and drink a lot of water.", "Entonces debo tomar una pastilla tres veces al día después de comer y beber mucha agua.", [["one tablet", "tablet", "pill"], ["three times", "three"], ["water", "drink"]], ["I have to take a pill three times a day after eating and drink lots of water."], "So I should take..."),
  T("Exactly. If you're not feeling better in a week, or if you develop a fever, come back and see me. Would you like a doctor's note for work?", "Exacto. Si no mejora en una semana o le da fiebre, vuelva. ¿Quiere un justificante para el trabajo?"),
  Y("Yes, please. I need to stay at home for two days. Thank you very much, doctor.", "Sí, por favor. Necesito quedarme en casa dos días. Muchas gracias, doctor.", [["yes", "please"], ["two days", "home", "stay"], ["thank"]], ["Yes please, I have to stay home for two days. Thanks a lot doctor."], "Yes, please..."),
  T("Of course. Before you go, a few quick questions about your lifestyle, because they can affect how fast you recover. Do you smoke, and do you do any exercise?", "Claro. Antes de irse, unas preguntas sobre su estilo de vida, porque pueden afectar la recuperación. ¿Fuma? ¿Hace ejercicio?"),
  Y("I don't smoke, and I usually exercise twice a week, but I'll rest until I feel better.", "No fumo y suelo hacer ejercicio dos veces por semana, pero descansaré hasta sentirme mejor.", [["don't smoke", "not smoke", "smoke"], ["exercise", "twice", "week"], ["rest", "better"]], ["I do not smoke. I exercise two times a week but I will rest until I am better."], "I don't smoke..."),
  T("That's sensible. The pharmacy is on the ground floor and it closes at seven, so please pick up your tablets today. Do you have any other questions for me?", "Es sensato. La farmacia está en la planta baja y cierra a las siete, así que recoja hoy las pastillas. ¿Tiene alguna otra pregunta?"),
  Y("Yes, can I drink coffee while I'm taking the tablets? And is it okay to go to work on Friday?", "Sí, ¿puedo tomar café mientras tomo las pastillas? ¿Y puedo ir a trabajar el viernes?", [["coffee", "drink"], ["tablets", "taking"], ["friday", "work"]], ["Can I have coffee with the tablets? And can I go to work on Friday?"], "Can I drink coffee...")])

TALK("weekend-trip", "Planning a weekend trip", "Proponer, opinar y decidir planes con un amigo", "B1.2", "daily", "Viajes y planes",
 "Hacer sugerencias, comparar opciones, estar de acuerdo o no y llegar a un acuerdo.",
 [["How about we go to the coast?", "¿Qué tal si vamos a la costa?"], ["I'd rather stay somewhere cheap.", "Preferiría quedarme en un sitio barato."], ["It depends on the weather.", "Depende del clima."], ["That works for me.", "Me parece bien."], ["Let's split the cost.", "Dividamos el gasto."]],
 [T("Hey! So, about this weekend. I was thinking we could get out of the city for a couple of days. Any ideas?", "¡Oye! Sobre este fin de semana. Pensaba que podríamos salir de la ciudad un par de días. ¿Alguna idea?"),
  Y("How about we go to the coast? It's only two hours by train and we could relax on the beach.", "¿Qué tal si vamos a la costa? Son solo dos horas en tren y podríamos relajarnos en la playa.", [["how about", "why don't we", "let's", "we could"], ["coast", "beach"], ["train", "two hours"]], ["Why don't we go to the beach? It takes two hours by train and we can relax."], "How about we go..."),
  T("Hmm, that sounds nice, but I checked the forecast and it might rain on Saturday. The mountains could be a better option, and there's a lovely village with hiking trails. The only problem is that it's a bit more expensive to get there.", "Suena bien, pero vi el pronóstico y quizás llueva el sábado. La montaña podría ser mejor, con un pueblo con senderos. El problema es que llegar cuesta un poco más."),
  C("Why does the friend prefer the mountains?", ["The weather might be bad at the coast", "The train is faster", "It is cheaper"], 0, "¿Por qué prefiere la montaña?"),
  Y("I'd rather stay somewhere cheap, but I like hiking. Is there a bus instead of the train?", "Preferiría un sitio barato, pero me gusta el senderismo. ¿Hay un autobús en lugar del tren?", [["rather", "prefer", "cheap"], ["hiking", "like"], ["bus", "instead"]], ["I prefer something cheap but I enjoy hiking. Can we take a bus instead?"], "I'd rather..."),
  T("Good thinking. There's a bus at eight in the morning that costs half the price, although it takes three hours. We could also share a car with my cousin, who's going that way anyway.", "Buena idea. Hay un autobús a las ocho que cuesta la mitad, aunque tarda tres horas. También podríamos compartir coche con mi primo, que va para allá."),
  Y("Sharing a car sounds better because it's faster. Let's split the cost of the petrol with him.", "Compartir el coche suena mejor porque es más rápido. Dividamos la gasolina con él.", [["car", "sharing", "share"], ["split", "cost", "petrol", "share"], ["faster", "better"]], ["Going by car with your cousin is better, it is faster. We can share the petrol cost."], "Sharing a car..."),
  T("Deal. Now, where should we stay? There's a hostel in the village, or a small guesthouse that includes breakfast. The guesthouse is twenty euros more per night.", "Trato hecho. ¿Dónde nos quedamos? Hay un hostal o una casa de huéspedes con desayuno incluido, veinte euros más por noche."),
  C("What is the difference between the two places?", ["The guesthouse includes breakfast and costs more", "The hostel has a pool", "They cost the same"], 0, "¿Cuál es la diferencia?"),
  Y("If breakfast is included, I think the guesthouse is worth it. It depends on our budget, though.", "Si el desayuno está incluido, creo que la casa de huéspedes vale la pena. Aunque depende de nuestro presupuesto.", [["breakfast", "included"], ["worth", "guesthouse"], ["depends", "budget"]], ["The guesthouse is worth the money with breakfast. But it depends on the budget."], "It depends on..."),
  T("Fair enough. Let's book the guesthouse for one night and see how we feel. Are you free to leave on Friday after work?", "Justo. Reservemos la casa de huéspedes una noche y veamos. ¿Puedes salir el viernes después del trabajo?"),
  Y("Friday after six works for me. I'll pack tonight and bring some snacks for the trip.", "El viernes después de las seis me viene bien. Prepararé la maleta esta noche y llevaré snacks.", [["friday", "six", "works", "fine"], ["pack", "snacks", "bring"]], ["Friday at six is fine for me. I will pack tonight and bring snacks."], "Friday works for me...")])

TALK("returning-item", "Returning something to a shop", "Pedir un cambio o reembolso con educación y firmeza", "B1.2", "daily", "Compras y servicios",
 "Explicar un problema con un producto y negociar una solución.",
 [["I'd like to return this.", "Quisiera devolver esto."], ["It doesn't work properly.", "No funciona bien."], ["I've got the receipt.", "Tengo el recibo."], ["Could I get a refund instead?", "¿Podría obtener un reembolso?"], ["That's not what I was expecting.", "Eso no es lo que esperaba."]],
 [T("Good afternoon. How can I help you today?", "Buenas tardes. ¿En qué puedo ayudarle?"),
  Y("Hi, I bought these headphones last week, but the left side doesn't work properly. I'd like to return them.", "Hola, compré estos auriculares la semana pasada pero el lado izquierdo no funciona bien. Quisiera devolverlos.", [["headphones", "these"], ["left", "doesn't work", "not work", "broken"], ["return", "refund", "exchange"]], ["I got these headphones last week and the left one is not working well. I want to return them."], "I bought these headphones..."),
  T("I'm sorry to hear that. Do you have the receipt with you? And may I ask, have you tried them with a different phone? Sometimes it's just a connection problem.", "Lamento oírlo. ¿Tiene el recibo? ¿Los ha probado con otro teléfono? A veces es solo un problema de conexión."),
  Y("Yes, here's the receipt. I tried them with two different phones and the problem is the same.", "Sí, aquí está el recibo. Los probé con dos teléfonos y el problema es el mismo.", [["receipt", "here"], ["two", "different phones", "tried"], ["same", "problem"]], ["Here is the receipt. I tested them on two phones and it is the same problem."], "Here's the receipt..."),
  T("Thank you. Everything looks fine with the receipt. Unfortunately, we don't have the same model in stock at the moment, but I can offer you a similar pair from another brand, or store credit for the full amount.", "Gracias. El recibo está bien. Lamentablemente no tenemos el mismo modelo en stock, pero puedo ofrecerle otro par de otra marca o crédito en tienda por el total."),
  C("What two options does the shop offer?", ["A similar pair or store credit", "A repair or a discount", "A refund or a gift card"], 0, "¿Qué dos opciones ofrece la tienda?"),
  Y("I'd prefer a refund to my card, if that's possible. I'm not sure I want another brand.", "Preferiría un reembolso a mi tarjeta, si es posible. No estoy seguro de querer otra marca.", [["refund", "money back"], ["card", "prefer"], ["another brand", "not sure", "other brand"]], ["Could I get my money back on my card please? I don't really want a different brand."], "I'd prefer a refund..."),
  T("Let me check with my manager. Well, normally we only give store credit after seven days, but since the product is faulty, I think we can make an exception. It'll take three to five working days to appear in your account.", "Déjeme consultar con mi gerente. Normalmente solo damos crédito pasados siete días, pero como el producto es defectuoso, podemos hacer una excepción. Tardará de tres a cinco días hábiles."),
  Y("That's great, thank you for your help. Just to be sure, it will take three to five working days, right?", "Genial, gracias por su ayuda. Solo para confirmar, tardará de tres a cinco días hábiles, ¿verdad?", [["thank"], ["three", "five", "days", "working days"], ["right", "sure", "confirm"]], ["Thanks for helping me. So it takes three to five working days, correct?"], "Just to be sure..."),
  T("That's right. You'll get a confirmation email today. Is there anything else I can help you with?", "Correcto. Recibirá un correo de confirmación hoy. ¿Algo más en lo que pueda ayudarle?"),
  Y("No, that's everything. Thanks again and have a good afternoon.", "No, eso es todo. Gracias de nuevo y buena tarde.", [["no", "that's all", "everything"], ["thanks", "thank"]], ["No, nothing else. Thank you very much, have a nice afternoon."], "No, that's everything...")])

TALK("work-life", "Work-life balance and stress", "Debatir sobre trabajo, descanso y hábitos con opiniones matizadas", "B2.1", "daily", "Trabajo y bienestar",
 "Dar opiniones, justificar, matizar ('although', 'that said') y responder a contraargumentos.",
 [["In my experience,...", "En mi experiencia..."], ["That said,...", "Dicho esto,..."], ["It's easier said than done.", "Es más fácil decirlo que hacerlo."], ["I couldn't agree more.", "Totalmente de acuerdo."], ["It comes down to priorities.", "Se reduce a las prioridades."]],
 [T("So, I read an article this morning saying that people who work from home actually work longer hours than people in offices. Does that match your experience?", "Leí esta mañana un artículo que decía que quienes trabajan desde casa trabajan más horas que en oficina. ¿Coincide con tu experiencia?"),
  Y("In my experience, yes. When your home is your office, it's hard to switch off at the end of the day.", "En mi experiencia sí. Cuando tu casa es tu oficina, es difícil desconectar al final del día.", [["in my experience", "for me", "i think"], ["hard", "difficult", "switch off", "disconnect"], ["home", "office"]], ["Yes, for me it is true. It is difficult to disconnect when you work at home."], "In my experience..."),
  T("Exactly. I find that the boundary between work and personal life just disappears. I catch myself answering emails at ten at night, and then I wonder why I can't sleep. I know I should set limits, but it's easier said than done.", "Exacto. Siento que el límite entre trabajo y vida personal desaparece. Me pillo respondiendo correos a las diez de la noche y luego me pregunto por qué no duermo. Sé que debería poner límites, pero es más fácil decirlo que hacerlo."),
  C("What is the speaker's problem?", ["Emails late at night affect their sleep", "They have too many meetings", "They dislike working from home"], 0, "¿Cuál es el problema del hablante?"),
  Y("That said, I've found that having a fixed schedule helps. I close my laptop at six and I don't check my phone.", "Dicho esto, he visto que tener un horario fijo ayuda. Cierro la laptop a las seis y no reviso el teléfono.", [["schedule", "routine", "fixed"], ["six", "close", "laptop", "stop"], ["phone", "don't check", "not check"]], ["Even so, a fixed schedule works for me. I shut my laptop at six and I do not look at my phone."], "That said..."),
  T("That's a good strategy, though I imagine it depends on your boss. In my company there's an unwritten rule that you should answer messages immediately, even after hours. If you don't, people think you're not committed.", "Buena estrategia, aunque imagino que depende del jefe. En mi empresa hay una regla no escrita: responder mensajes de inmediato, incluso fuera de horario. Si no, piensan que no te comprometes."),
  Y("I see your point, but I think it comes down to setting expectations early. If you're clear about your availability, most people respect it.", "Entiendo tu punto, pero creo que se reduce a fijar expectativas desde el principio. Si eres claro con tu disponibilidad, la mayoría lo respeta.", [["see your point", "understand", "i see"], ["expectations", "clear", "early"], ["availability", "respect", "hours"]], ["I understand you, but it depends on making clear rules early. People usually respect clear availability."], "I see your point, but..."),
  T("Maybe. Although in a big company it's not that simple. Anyway, what do you do to relax? I've been trying to take up something that has nothing to do with screens, like painting or running.", "Quizás. Aunque en una empresa grande no es tan simple. ¿Qué haces tú para relajarte? Intento empezar algo sin pantallas, como pintar o correr."),
  C("What does the speaker want to find?", ["An activity without screens", "A new job", "A quieter office"], 0, "¿Qué quiere encontrar el hablante?"),
  Y("I usually go for a long walk or cook something elaborate. It helps me clear my head and stop thinking about work.", "Suelo dar un paseo largo o cocinar algo elaborado. Me ayuda a despejar la mente y dejar de pensar en el trabajo.", [["walk", "cook", "cooking"], ["clear my head", "relax", "help"], ["work", "thinking"]], ["Normally I take a long walk or make a complicated meal. It relaxes my mind so I don't think about work."], "I usually go for..."),
  T("Cooking is a great idea, actually. Maybe you could give me a recipe sometime. Well, this was a really interesting conversation. I should get back to work before my boss sends me an email!", "Cocinar es buena idea. Quizás me pases una receta. Fue una conversación interesante. ¡Debo volver al trabajo antes de que mi jefe me escriba!"),
  Y("Ha, of course. I'll send you a recipe this weekend. It was great talking to you, and don't work too late tonight!", "Claro. Te enviaré una receta este fin de semana. Fue un gusto hablar contigo, ¡y no trabajes hasta tarde hoy!", [["recipe", "send"], ["weekend", "this weekend"], ["talking", "great", "late"]], ["Sure, I will send you a recipe on the weekend. Nice talking to you, don't work late."], "I'll send you...")], minutes=10)

TALK("interview", "A job interview", "Responder preguntas de entrevista con ejemplos concretos", "B2.1", "daily", "Trabajo",
 "Hablar de tu experiencia, fortalezas, un desafío superado y hacer preguntas al entrevistador.",
 [["I have three years of experience in...", "Tengo tres años de experiencia en..."], ["One of my strengths is...", "Una de mis fortalezas es..."], ["I took the initiative to...", "Tomé la iniciativa de..."], ["As a result,...", "Como resultado,..."], ["Could you tell me more about the team?", "¿Podría contarme más sobre el equipo?"]],
 [T("Thanks for coming in today. To start, could you tell me a bit about yourself and your background?", "Gracias por venir hoy. Para empezar, ¿podría hablarme un poco de usted y su trayectoria?"),
  Y("Of course. I have three years of experience as a developer, mainly building web applications for small businesses.", "Claro. Tengo tres años de experiencia como desarrollador, principalmente creando aplicaciones web para pequeños negocios.", [["three years", "years", "experience"], ["developer", "web", "applications", "software"], ["small businesses", "businesses", "mainly"]], ["Sure. I've worked three years as a developer, mostly making web apps for small companies."], "I have three years..."),
  T("Interesting. What would you say is your biggest strength, and how has it helped you in your previous roles?", "Interesante. ¿Cuál diría que es su mayor fortaleza y cómo le ha ayudado en sus puestos anteriores?"),
  Y("One of my strengths is learning quickly. For example, I taught myself a new framework in a month, which allowed our team to launch on time.", "Una de mis fortalezas es aprender rápido. Por ejemplo, aprendí un framework nuevo en un mes, lo que permitió lanzar a tiempo.", [["strength", "learning", "learn quickly"], ["framework", "new", "month", "example"], ["launch", "on time", "team"]], ["I learn fast. For instance, I studied a new framework in one month and the team could launch on time."], "One of my strengths..."),
  T("That's impressive. Now, tell me about a time when something went wrong on a project. How did you handle it?", "Impresionante. Ahora cuénteme sobre una vez que algo salió mal en un proyecto. ¿Cómo lo manejó?"),
  C("What is the interviewer asking about?", ["A time something went wrong", "The salary expectations", "Plans for the future"], 0, "¿Sobre qué pregunta el entrevistador?"),
  Y("Last year, a deployment broke the payment system. I took the initiative to roll it back, and as a result we lost only twenty minutes of sales.", "El año pasado, un despliegue rompió el sistema de pagos. Tomé la iniciativa de revertirlo y, como resultado, solo perdimos veinte minutos de ventas.", [["deployment", "payment", "broke", "problem"], ["initiative", "roll back", "fixed", "solved"], ["result", "twenty minutes", "lost"]], ["Last year a release broke payments. I decided to undo it quickly, so we only lost twenty minutes of sales."], "Last year, a deployment..."),
  T("Good. Communication is essential here. How do you usually explain technical problems to people who aren't technical, like our sales team?", "Bien. La comunicación es esencial aquí. ¿Cómo explica normalmente los problemas técnicos a personas no técnicas, como nuestro equipo de ventas?"),
  Y("I try to avoid jargon and use simple analogies. I also focus on the impact on customers rather than the technical details.", "Intento evitar la jerga y usar analogías simples. También me centro en el impacto para los clientes más que en los detalles técnicos.", [["avoid", "jargon", "simple"], ["analogies", "examples", "explain"], ["impact", "customers", "focus"]], ["I use simple words and examples, not technical terms. I talk about what it means for the customers."], "I try to avoid jargon..."),
  T("That makes sense. Well, that's all from my side. Do you have any questions for us?", "Tiene sentido. Eso es todo de mi parte. ¿Tiene alguna pregunta para nosotros?"),
  Y("Yes, could you tell me more about the team I would be working with, and what a typical week looks like?", "Sí, ¿podría contarme más sobre el equipo con el que trabajaría y cómo es una semana típica?", [["tell me more", "could you", "team"], ["typical week", "week", "looks like"]], ["Yes, can you explain more about the team and what a normal week is like?"], "Could you tell me more..."),
  T("Of course. The team has six developers, and we do short daily meetings and a longer planning session every Monday. We'll be in touch by Friday. Thanks again for your time.", "Claro. El equipo tiene seis desarrolladores, con reuniones diarias cortas y una sesión de planificación los lunes. Le contactaremos antes del viernes. Gracias por su tiempo."),
  Y("Thank you for the opportunity. I look forward to hearing from you, and have a great day.", "Gracias por la oportunidad. Espero saber de ustedes. Que tengan un gran día.", [["thank", "opportunity"], ["look forward", "hearing"]], ["Thanks for the chance. I hope to hear from you soon. Have a nice day."], "I look forward to...")], minutes=10)

TALK("dev-standup", "The daily stand-up", "Contar tu avance, tus bloqueos y tus planes en una reunión diaria", "B1.2", "dev", "Desarrollo de software",
 "Usar tiempos verbales correctos para 'ayer / hoy / bloqueos' y pedir ayuda.",
 [["Yesterday I worked on...", "Ayer trabajé en..."], ["Today I'm going to...", "Hoy voy a..."], ["I'm blocked by...", "Estoy bloqueado por..."], ["Could you take a look at my pull request?", "¿Podrías revisar mi pull request?"], ["It should be done by Thursday.", "Debería estar listo el jueves."]],
 [T("Good morning, everyone. Let's start the stand-up. Luis, could you go first? What did you work on yesterday?", "Buenos días a todos. Empecemos el stand-up. Luis, ¿puedes empezar tú? ¿En qué trabajaste ayer?"),
  Y("Yesterday I worked on the login page. I fixed the validation error and I wrote two tests for it.", "Ayer trabajé en la página de login. Arreglé el error de validación y escribí dos pruebas.", [["yesterday", "worked"], ["login", "validation", "fixed"], ["tests", "wrote"]], ["Yesterday I was working on the login page. I fixed the validation bug and wrote two tests."], "Yesterday I worked on..."),
  T("Nice. And what's your plan for today? Remember that we have the release on Thursday, so we need to prioritise.", "Bien. ¿Y cuál es tu plan para hoy? Recuerda que el jueves es el lanzamiento, así que hay que priorizar."),
  Y("Today I'm going to connect the login page to the API and start on the password reset feature.", "Hoy voy a conectar la página de login a la API y empezar con la función de restablecer contraseña.", [["today", "going to"], ["api", "connect"], ["password reset", "password", "feature"]], ["Today I will connect the login page with the API and begin the password reset feature."], "Today I'm going to..."),
  T("Sounds good. Any blockers? Is there anything preventing you from moving forward?", "Suena bien. ¿Algún bloqueo? ¿Algo te impide avanzar?"),
  Y("Yes, I'm blocked by the staging server. It's been down since last night, so I can't test my changes.", "Sí, estoy bloqueado por el servidor de staging. Está caído desde anoche y no puedo probar mis cambios.", [["blocked", "problem", "issue"], ["staging", "server", "down"], ["test", "can't", "cannot"]], ["I have a blocker, the staging server has been down since last night and I cannot test."], "I'm blocked by..."),
  T("Right, thanks for flagging that. Priya, you set up that server, right? Could you look into it right after this meeting? It's affecting a couple of people.", "Gracias por avisarlo. Priya, tú configuraste ese servidor, ¿no? ¿Podrías revisarlo justo después de la reunión? Afecta a varias personas."),
  C("Who is asked to fix the staging server?", ["Luis", "Priya", "The manager"], 1, "¿A quién le piden arreglar el servidor?"),
  Y("Thanks, Priya. Also, could someone take a look at my pull request? It's a small change, but I'd like a second pair of eyes.", "Gracias, Priya. Además, ¿alguien podría revisar mi pull request? Es un cambio pequeño pero quisiera una segunda opinión.", [["thanks", "priya"], ["pull request", "take a look", "review"], ["second", "eyes", "opinion", "small"]], ["Thank you Priya. Can somebody review my pull request? It is small but I want another person to check it."], "Could someone take a look..."),
  T("I can do that after lunch. When do you think the password reset will be ready? I'd like to give the client an update.", "Yo puedo hacerlo después del almuerzo. ¿Cuándo crees que estará lista la función de contraseña? Quiero dar una actualización al cliente."),
  Y("It should be done by Wednesday afternoon, as long as the staging server is back up today.", "Debería estar lista el miércoles por la tarde, siempre que el servidor de staging vuelva hoy.", [["wednesday", "should be done", "ready"], ["as long as", "if", "server", "staging"]], ["It will be ready by Wednesday afternoon if the staging server works again today."], "It should be done by...")], dev=1, minutes=8)

TALK("dev-bug", "Explaining a bug to a teammate", "Describir un error, reproducirlo y proponer una solución", "B2.1", "dev", "Desarrollo de software",
 "Explicar qué pasa, cuándo pasa, qué has probado y qué propones hacer.",
 [["It only happens when...", "Solo pasa cuando..."], ["I managed to reproduce it.", "Logré reproducirlo."], ["The root cause seems to be...", "La causa raíz parece ser..."], ["I'd suggest we...", "Sugeriría que..."], ["In the meantime, we can...", "Mientras tanto, podemos..."]],
 [T("Hey Luis, thanks for jumping on a call. QA says the checkout page sometimes freezes on mobile. Have you been able to look into it?", "Hola Luis, gracias por unirte a la llamada. QA dice que la página de pago a veces se congela en móvil. ¿Has podido revisarlo?"),
  Y("Yes, I managed to reproduce it. It only happens when the user taps the pay button twice very quickly.", "Sí, logré reproducirlo. Solo pasa cuando el usuario toca el botón de pagar dos veces muy rápido.", [["reproduce", "managed"], ["only happens", "when", "twice"], ["pay button", "button", "taps"]], ["Yes, I could reproduce it. It happens only if the user presses the pay button twice fast."], "I managed to reproduce it..."),
  T("Interesting. So the second tap is causing something. Did you check the logs? Sometimes the error is hiding there, and it could be a network timeout rather than a frontend issue.", "Interesante. El segundo toque provoca algo. ¿Revisaste los logs? A veces el error está ahí y podría ser un timeout de red y no un problema del frontend."),
  Y("I did. The logs show two requests reaching the server at the same time, so the root cause seems to be a race condition.", "Sí. Los logs muestran dos peticiones llegando al servidor a la vez, así que la causa raíz parece ser una condición de carrera.", [["logs", "checked"], ["two requests", "same time", "requests"], ["root cause", "race condition", "cause"]], ["Yes. The logs show two requests arriving together, so the main cause looks like a race condition."], "The logs show..."),
  C("What is the root cause according to Luis?", ["A slow network", "A race condition from two requests", "A missing image"], 1, "¿Cuál es la causa según Luis?"),
  T("That makes sense. So what would you suggest? We can't ask users to tap only once, obviously, and we're releasing the new version on Friday.", "Tiene sentido. ¿Qué sugieres? No podemos pedirle a los usuarios que toquen una vez, y el viernes sale la nueva versión."),
  Y("I'd suggest we disable the button after the first tap and make the server ignore duplicate requests. That way we fix it on both sides.", "Sugeriría deshabilitar el botón tras el primer toque y hacer que el servidor ignore peticiones duplicadas. Así lo arreglamos en ambos lados.", [["suggest", "disable", "button"], ["server", "ignore", "duplicate"], ["both sides", "both", "way"]], ["I suggest we turn off the button after the first tap and let the server ignore duplicate requests, so both sides are protected."], "I'd suggest we..."),
  T("Solid plan. The server-side fix is important, because a client-side fix alone can always be bypassed. How long do you think it will take, including tests?", "Buen plan. El arreglo del servidor es importante, porque uno solo en el cliente puede saltarse. ¿Cuánto tardarías incluyendo pruebas?"),
  Y("I think about a day and a half, including tests. In the meantime, we can add a warning to the release notes.", "Creo que día y medio, incluyendo pruebas. Mientras tanto podemos añadir una advertencia en las notas de la versión.", [["day", "half", "time", "hours"], ["tests", "including"], ["in the meantime", "meantime", "release notes", "warning"]], ["Around a day and a half with tests. Meanwhile we could put a warning in the release notes."], "In the meantime..."),
  T("Perfect. Let's open a ticket and assign it to you. Thanks for the clear explanation, Luis. It made my job much easier.", "Perfecto. Abramos un ticket y te lo asigno. Gracias por la explicación clara, Luis. Me facilitó mucho el trabajo."),
  Y("No problem. I'll write the ticket right now, and I'll ping you when the pull request is ready for review.", "Sin problema. Escribo el ticket ahora mismo y te aviso cuando el pull request esté listo para revisión.", [["ticket", "write"], ["ping", "tell", "let you know", "message"], ["pull request", "ready", "review"]], ["No worries. I will create the ticket now and let you know when the pull request is ready to review."], "I'll write the ticket...")], dev=2, minutes=10)

os.makedirs(OUT, exist_ok=True)
for f in os.listdir(OUT):
    if f.endswith(".json"): os.remove(os.path.join(OUT, f))
idx = []
for t in TALKS:
    assert re.fullmatch(r"[\w-]+", t["id"])
    json.dump(t, open(os.path.join(OUT, t["id"] + ".json"), "w", encoding="utf-8"), ensure_ascii=False, separators=(",", ":"))
    idx.append({k: t[k] for k in ("id", "title", "es", "level", "track", "topic", "minutes") if k in t} | ({"dev": t["dev"]} if "dev" in t else {}) | {"turns": sum(1 for x in t["turns"] if "y" in x)})
json.dump(idx, open(os.path.join(OUT, "index.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print(len(TALKS), "conversaciones ->", OUT)
