#!/usr/bin/env python3
"""Genera data/talks/*.json e index.json desde las definiciones de este archivo.
Añadir una conversación = añadir un bloque TALK(...) y ejecutar: python3 tools/build_talks.py"""
import json, os, re
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "talks")
TALKS = []
def T(en, es): return {"t": en, "es": es}
def Y(say, es, keys, alts=(), hint=""): return {"y": {"say": say, "es": es, "keys": keys, "alts": list(alts), "hint": hint}}
def C(q, opts, a, es=""): return {"c": {"q": q, "o": opts, "a": a, "es": es}}
def TALK(id, title, es, level, track, topic, goal, phrases, turns, dev=None, minutes=8):
    TALKS.append(dict(id=id, title=title, es=es, level=level, track=track, topic=topic, goal=goal, minutes=minutes, phrases=phrases, turns=turns, **({"dev": dev} if dev else {})))

TALK("neighbour", "Meeting a new neighbour", "Presentarte y conversar con un vecino nuevo", "B1.1", "daily", "Vida diaria",
 "Presentarte, hablar de dónde vives, de tu rutina y hacer planes sencillos.",
 [["Nice to meet you.", "Mucho gusto."], ["I've just moved in.", "Acabo de mudarme."], ["How long have you lived here?", "¿Cuánto tiempo llevas viviendo aquí?"], ["It's a bit noisy, but I'm used to it.", "Es algo ruidoso, pero estoy acostumbrado."], ["We should grab a coffee sometime.", "Deberíamos tomar un café algún día."]],
 [T("Oh, hi! You must be the new neighbour. I'm Sarah, I live in the flat next door. Welcome to the building!", "¡Hola! Debes ser el vecino nuevo. Soy Sarah, vivo en el piso de al lado. ¡Bienvenido al edificio!"),
  Y("Hi Sarah, nice to meet you. I'm Luis, I've just moved in last week.", "Hola Sarah, mucho gusto. Soy Luis, me mudé la semana pasada.", [["nice to meet you", "pleased to meet you", "good to meet you"], ["luis", "moved", "moved in"]], ["Nice to meet you Sarah. My name is Luis and I moved here last week."], "Nice to meet you..."),
  T("Great! So, where are you from originally? I can hear a bit of an accent, and I love it.", "¡Genial! ¿De dónde eres originalmente? Noto un poco de acento y me encanta."),
  Y("I'm from Venezuela, but I've been living abroad for a few years now.", "Soy de Venezuela, pero llevo unos años viviendo fuera.", [["venezuela", "from"], ["years", "abroad", "living"]], ["I come from Venezuela and I have lived abroad for some years."], "I'm from..."),
  T("That's interesting. Honestly, the neighbourhood is great, but the walls are quite thin, so you might hear the neighbours upstairs. They're nice, though. They have a dog called Max who barks at the postman every morning.", "Qué interesante. Sinceramente, el barrio es genial pero las paredes son finas, y quizás oigas a los vecinos de arriba. Son amables. Tienen un perro, Max, que le ladra al cartero cada mañana."),
  C("What does Sarah warn him about?", ["The rent is expensive", "The walls are thin and a dog barks", "The building has no elevator"], 1, "¿De qué le advierte Sarah?"),
  Y("Don't worry, I'm used to noise. I actually work from home, so I'll get to meet Max.", "No te preocupes, estoy acostumbrado al ruido. Trabajo desde casa, así que conoceré a Max.", [["used to", "don't worry", "no problem"], ["work", "home"]], ["It's fine, I don't mind the noise. I work from home so I will meet Max."], "I work from home..."),
  T("Oh, what do you do? I'm a nurse, so my schedule is all over the place. Sometimes I work nights and sleep all day.", "¿A qué te dedicas? Yo soy enfermera, así que mi horario es un caos. A veces trabajo de noche y duermo de día."),
  Y("I'm a software developer. I write code for a small company and I work remotely.", "Soy desarrollador de software. Escribo código para una empresa pequeña y trabajo a distancia.", [["software", "developer", "programmer"], ["work", "remotely", "company", "code"]], ["I work as a programmer for a small company from home."], "I'm a software developer..."),
  T("Nice! Listen, there's a small supermarket two streets down, and the bakery on the corner is fantastic. If you ever need anything, just knock. Oh, and we're having a small barbecue on the roof on Saturday. You should come!", "¡Genial! Mira, hay un supermercado pequeño a dos calles, y la panadería de la esquina es fantástica. Si necesitas algo, toca la puerta. Y el sábado hacemos una barbacoa en la azotea. ¡Deberías venir!"),
  C("What is happening on Saturday?", ["A building meeting", "A barbecue on the roof", "A dinner at the bakery"], 1, "¿Qué pasa el sábado?"),
  Y("That sounds great, I'd love to come. Can I bring something to drink?", "Suena genial, me encantaría ir. ¿Puedo llevar algo de beber?", [["love to", "would like", "sounds great", "sounds good"], ["bring", "drink"]], ["Sounds good, I would love to come. Should I bring a drink?"], "I'd love to come..."),
  T("Perfect! Just bring yourself, but some juice is always welcome. It starts at six. See you then, Luis!", "¡Perfecto! Tráete a ti mismo, pero un jugo siempre viene bien. Empieza a las seis. ¡Nos vemos, Luis!"),
  Y("Thanks, Sarah. See you on Saturday at six. Have a nice day!", "Gracias, Sarah. Nos vemos el sábado a las seis. ¡Que tengas buen día!", [["thanks", "thank you"], ["saturday", "six", "see you"]], ["Thank you Sarah, see you Saturday at six. Have a good day."], "See you on Saturday...")])

TALK("doctor", "At the doctor's", "Describir síntomas y entender indicaciones médicas", "B1.1", "daily", "Salud",
 "Explicar cómo te sientes, desde cuándo, y entender recomendaciones.",
 [["I've had a headache since Monday.", "Tengo dolor de cabeza desde el lunes."], ["It hurts here.", "Me duele aquí."], ["I'm allergic to penicillin.", "Soy alérgico a la penicilina."], ["How often should I take it?", "¿Cada cuánto debo tomarlo?"], ["Get plenty of rest.", "Descansa mucho."]],
 [T("Good morning, please take a seat. So, what seems to be the problem today?", "Buenos días, siéntese. ¿Cuál parece ser el problema hoy?"),
  Y("I've had a sore throat and a cough since Monday, and I feel very tired.", "Tengo dolor de garganta y tos desde el lunes y me siento muy cansado.", [["sore throat", "throat"], ["cough"], ["since monday", "monday", "days"]], ["My throat hurts and I have had a cough since Monday. I am very tired."], "I've had a sore throat..."),
  T("I see. Have you had a fever, or any trouble breathing? Also, are you taking any medication at the moment?", "Entiendo. ¿Ha tenido fiebre o problemas para respirar? ¿Toma algún medicamento ahora?"),
  Y("No fever, and I can breathe normally. I'm not taking any medication, but I'm allergic to penicillin.", "Sin fiebre y respiro normal. No tomo medicación, pero soy alérgico a la penicilina.", [["no fever", "fever"], ["allergic", "penicillin"], ["not taking", "no medication", "medication"]], ["I don't have a fever and I breathe fine. I don't take medicine. I have an allergy to penicillin."], "I'm allergic to..."),
  C("What is important the patient tells the doctor?", ["He has no fever", "He is allergic to penicillin", "He takes vitamins"], 1, "¿Qué dato importante dice el paciente?"),
  T("Thank you, that's very useful. It looks like a viral infection, so antibiotics won't help. I'll give you something for the throat. Take one tablet three times a day, after meals, for five days. Drink plenty of water and get as much rest as you can.", "Gracias, es muy útil. Parece una infección viral, así que los antibióticos no ayudarían. Le daré algo para la garganta. Una pastilla tres veces al día, después de comer, durante cinco días. Beba mucha agua y descanse."),
  C("How often should he take the tablet?", ["Once a day", "Three times a day", "Only at night"], 1, "¿Cada cuánto debe tomarla?"),
  Y("So I should take one tablet three times a day after meals, and drink a lot of water.", "Entonces debo tomar una pastilla tres veces al día después de comer y beber mucha agua.", [["one tablet", "tablet", "pill"], ["three times", "three"], ["water", "drink"]], ["I have to take a pill three times a day after eating and drink lots of water."], "So I should take..."),
  T("Exactly. If you're not feeling better in a week, or if you develop a fever, come back and see me. Would you like a doctor's note for work?", "Exacto. Si no mejora en una semana o le da fiebre, vuelva. ¿Quiere un justificante para el trabajo?"),
  Y("Yes, please. I need to stay at home for two days. Thank you very much, doctor.", "Sí, por favor. Necesito quedarme en casa dos días. Muchas gracias, doctor.", [["yes", "please"], ["two days", "home", "stay"], ["thank"]], ["Yes please, I have to stay home for two days. Thanks a lot doctor."], "Yes, please..."),
  T("Of course. Before you go, a few quick questions about your lifestyle, because they can affect how fast you recover. Do you smoke, and do you do any exercise?", "Claro. Antes de irse, unas preguntas sobre su estilo de vida, porque pueden afectar la recuperación. ¿Fuma? ¿Hace ejercicio?"),
  Y("I don't smoke, and I usually exercise twice a week, but I'll rest until I feel better.", "No fumo y suelo hacer ejercicio dos veces por semana, pero descansaré hasta sentirme mejor.", [["don't smoke", "not smoke", "smoke"], ["exercise", "twice", "week"], ["rest", "better"]], ["I do not smoke. I exercise two times a week but I will rest until I am better."], "I don't smoke..."),
  T("That's sensible. The pharmacy is on the ground floor and it closes at seven, so please pick up your tablets today. Do you have any other questions for me?", "Es sensato. La farmacia está en la planta baja y cierra a las siete, así que recoja hoy las pastillas. ¿Tiene alguna otra pregunta?"),
  Y("Yes, can I drink coffee while I'm taking the tablets? And is it okay to go to work on Friday?", "Sí, ¿puedo tomar café mientras tomo las pastillas? ¿Y puedo ir a trabajar el viernes?", [["coffee", "drink"], ["tablets", "taking"], ["friday", "work"]], ["Can I have coffee with the tablets? And can I go to work on Friday?"], "Can I drink coffee...")])

TALK("weekend-trip", "Planning a weekend trip", "Proponer, opinar y decidir planes con un amigo", "B1.2", "daily", "Viajes",
 "Hacer sugerencias, comparar opciones, estar de acuerdo o no y llegar a un acuerdo.",
 [["How about we go to the coast?", "¿Qué tal si vamos a la costa?"], ["I'd rather stay somewhere cheap.", "Preferiría quedarme en un sitio barato."], ["It depends on the weather.", "Depende del clima."], ["That works for me.", "Me parece bien."], ["Let's split the cost.", "Dividamos el gasto."]],
 [T("Hey! So, about this weekend. I was thinking we could get out of the city for a couple of days. Any ideas?", "¡Oye! Sobre este fin de semana. Pensaba que podríamos salir de la ciudad un par de días. ¿Alguna idea?"),
  Y("How about we go to the coast? It's only two hours by train and we could relax on the beach.", "¿Qué tal si vamos a la costa? Son solo dos horas en tren y podríamos relajarnos en la playa.", [["how about", "why don't we", "let's", "we could"], ["coast", "beach"], ["train", "two hours"]], ["Why don't we go to the beach? It takes two hours by train and we can relax."], "How about we go..."),
  T("Hmm, that sounds nice, but I checked the forecast and it might rain on Saturday. The mountains could be a better option, and there's a lovely village with hiking trails. The only problem is that it's a bit more expensive to get there.", "Suena bien, pero vi el pronóstico y quizás llueva el sábado. La montaña podría ser mejor, con un pueblo con senderos. El problema es que llegar cuesta un poco más."),
  C("Why does the friend prefer the mountains?", ["The weather might be bad at the coast", "The train is faster", "It is cheaper"], 0, "¿Por qué prefiere la montaña?"),
  Y("I'd rather stay somewhere cheap, but I like hiking. Is there a bus instead of the train?", "Preferiría un sitio barato, pero me gusta el senderismo. ¿Hay un autobús en lugar del tren?", [["rather", "prefer", "cheap"], ["hiking", "like"], ["bus", "instead"]], ["I prefer something cheap but I enjoy hiking. Can we take a bus instead?"], "I'd rather..."),
  T("Good thinking. There's a bus at eight in the morning that costs half the price, although it takes three hours. We could also share a car with my cousin, who's going that way anyway.", "Buena idea. Hay un autobús a las ocho que cuesta la mitad, aunque tarda tres horas. También podríamos compartir coche con mi primo, que va para allá."),
  Y("Sharing a car sounds better because it's faster. Let's split the cost of the petrol with him.", "Compartir el coche suena mejor porque es más rápido. Dividamos la gasolina con él.", [["car", "sharing", "share"], ["split", "cost", "petrol", "share"], ["faster", "better"]], ["Going by car with your cousin is better, it is faster. We can share the petrol cost."], "Sharing a car..."),
  T("Deal. Now, where should we stay? There's a hostel in the village, or a small guesthouse that includes breakfast. The guesthouse is twenty euros more per night.", "Trato hecho. ¿Dónde nos quedamos? Hay un hostal o una casa de huéspedes con desayuno incluido, veinte euros más por noche."),
  C("What is the difference between the two places?", ["The guesthouse includes breakfast and costs more", "The hostel has a pool", "They cost the same"], 0, "¿Cuál es la diferencia?"),
  Y("If breakfast is included, I think the guesthouse is worth it. It depends on our budget, though.", "Si el desayuno está incluido, creo que la casa de huéspedes vale la pena. Aunque depende de nuestro presupuesto.", [["breakfast", "included"], ["worth", "guesthouse"], ["depends", "budget"]], ["The guesthouse is worth the money with breakfast. But it depends on the budget."], "It depends on..."),
  T("Fair enough. Let's book the guesthouse for one night and see how we feel. Are you free to leave on Friday after work?", "Justo. Reservemos la casa de huéspedes una noche y veamos. ¿Puedes salir el viernes después del trabajo?"),
  Y("Friday after six works for me. I'll pack tonight and bring some snacks for the trip.", "El viernes después de las seis me viene bien. Prepararé la maleta esta noche y llevaré snacks.", [["friday", "six", "works", "fine"], ["pack", "snacks", "bring"]], ["Friday at six is fine for me. I will pack tonight and bring snacks."], "Friday works for me...")])

TALK("returning-item", "Returning something to a shop", "Pedir un cambio o reembolso con educación y firmeza", "B1.2", "daily", "Compras",
 "Explicar un problema con un producto y negociar una solución.",
 [["I'd like to return this.", "Quisiera devolver esto."], ["It doesn't work properly.", "No funciona bien."], ["I've got the receipt.", "Tengo el recibo."], ["Could I get a refund instead?", "¿Podría obtener un reembolso?"], ["That's not what I was expecting.", "Eso no es lo que esperaba."]],
 [T("Good afternoon. How can I help you today?", "Buenas tardes. ¿En qué puedo ayudarle?"),
  Y("Hi, I bought these headphones last week, but the left side doesn't work properly. I'd like to return them.", "Hola, compré estos auriculares la semana pasada pero el lado izquierdo no funciona bien. Quisiera devolverlos.", [["headphones", "these"], ["left", "doesn't work", "not work", "broken"], ["return", "refund", "exchange"]], ["I got these headphones last week and the left one is not working well. I want to return them."], "I bought these headphones..."),
  T("I'm sorry to hear that. Do you have the receipt with you? And may I ask, have you tried them with a different phone? Sometimes it's just a connection problem.", "Lamento oírlo. ¿Tiene el recibo? ¿Los ha probado con otro teléfono? A veces es solo un problema de conexión."),
  Y("Yes, here's the receipt. I tried them with two different phones and the problem is the same.", "Sí, aquí está el recibo. Los probé con dos teléfonos y el problema es el mismo.", [["receipt", "here"], ["two", "different phones", "tried"], ["same", "problem"]], ["Here is the receipt. I tested them on two phones and it is the same problem."], "Here's the receipt..."),
  T("Thank you. Everything looks fine with the receipt. Unfortunately, we don't have the same model in stock at the moment, but I can offer you a similar pair from another brand, or store credit for the full amount.", "Gracias. El recibo está bien. Lamentablemente no tenemos el mismo modelo en stock, pero puedo ofrecerle otro par de otra marca o crédito en tienda por el total."),
  C("What two options does the shop offer?", ["A similar pair or store credit", "A repair or a discount", "A refund or a gift card"], 0, "¿Qué dos opciones ofrece la tienda?"),
  Y("I'd prefer a refund to my card, if that's possible. I'm not sure I want another brand.", "Preferiría un reembolso a mi tarjeta, si es posible. No estoy seguro de querer otra marca.", [["refund", "money back"], ["card", "prefer"], ["another brand", "not sure", "other brand"]], ["Could I get my money back on my card please? I don't really want a different brand."], "I'd prefer a refund..."),
  T("Let me check with my manager. Well, normally we only give store credit after seven days, but since the product is faulty, I think we can make an exception. It'll take three to five working days to appear in your account.", "Déjeme consultar con mi gerente. Normalmente solo damos crédito pasados siete días, pero como el producto es defectuoso, podemos hacer una excepción. Tardará de tres a cinco días hábiles."),
  Y("That's great, thank you for your help. Just to be sure, it will take three to five working days, right?", "Genial, gracias por su ayuda. Solo para confirmar, tardará de tres a cinco días hábiles, ¿verdad?", [["thank"], ["three", "five", "days", "working days"], ["right", "sure", "confirm"]], ["Thanks for helping me. So it takes three to five working days, correct?"], "Just to be sure..."),
  T("That's right. You'll get a confirmation email today. Is there anything else I can help you with?", "Correcto. Recibirá un correo de confirmación hoy. ¿Algo más en lo que pueda ayudarle?"),
  Y("No, that's everything. Thanks again and have a good afternoon.", "No, eso es todo. Gracias de nuevo y buena tarde.", [["no", "that's all", "everything"], ["thanks", "thank"]], ["No, nothing else. Thank you very much, have a nice afternoon."], "No, that's everything...")])

TALK("work-life", "Work-life balance and stress", "Debatir sobre trabajo, descanso y hábitos con opiniones matizadas", "B2.1", "daily", "Trabajo",
 "Dar opiniones, justificar, matizar ('although', 'that said') y responder a contraargumentos.",
 [["In my experience,...", "En mi experiencia..."], ["That said,...", "Dicho esto,..."], ["It's easier said than done.", "Es más fácil decirlo que hacerlo."], ["I couldn't agree more.", "Totalmente de acuerdo."], ["It comes down to priorities.", "Se reduce a las prioridades."]],
 [T("So, I read an article this morning saying that people who work from home actually work longer hours than people in offices. Does that match your experience?", "Leí esta mañana un artículo que decía que quienes trabajan desde casa trabajan más horas que en oficina. ¿Coincide con tu experiencia?"),
  Y("In my experience, yes. When your home is your office, it's hard to switch off at the end of the day.", "En mi experiencia sí. Cuando tu casa es tu oficina, es difícil desconectar al final del día.", [["in my experience", "for me", "i think"], ["hard", "difficult", "switch off", "disconnect"], ["home", "office"]], ["Yes, for me it is true. It is difficult to disconnect when you work at home."], "In my experience..."),
  T("Exactly. I find that the boundary between work and personal life just disappears. I catch myself answering emails at ten at night, and then I wonder why I can't sleep. I know I should set limits, but it's easier said than done.", "Exacto. Siento que el límite entre trabajo y vida personal desaparece. Me pillo respondiendo correos a las diez de la noche y luego me pregunto por qué no duermo. Sé que debería poner límites, pero es más fácil decirlo que hacerlo."),
  C("What is the speaker's problem?", ["Emails late at night affect their sleep", "They have too many meetings", "They dislike working from home"], 0, "¿Cuál es el problema del hablante?"),
  Y("That said, I've found that having a fixed schedule helps. I close my laptop at six and I don't check my phone.", "Dicho esto, he visto que tener un horario fijo ayuda. Cierro la laptop a las seis y no reviso el teléfono.", [["schedule", "routine", "fixed"], ["six", "close", "laptop", "stop"], ["phone", "don't check", "not check"]], ["Even so, a fixed schedule works for me. I shut my laptop at six and I do not look at my phone."], "That said..."),
  T("That's a good strategy, though I imagine it depends on your boss. In my company there's an unwritten rule that you should answer messages immediately, even after hours. If you don't, people think you're not committed.", "Buena estrategia, aunque imagino que depende del jefe. En mi empresa hay una regla no escrita: responder mensajes de inmediato, incluso fuera de horario. Si no, piensan que no te comprometes."),
  Y("I see your point, but I think it comes down to setting expectations early. If you're clear about your availability, most people respect it.", "Entiendo tu punto, pero creo que se reduce a fijar expectativas desde el principio. Si eres claro con tu disponibilidad, la mayoría lo respeta.", [["see your point", "understand", "i see"], ["expectations", "clear", "early"], ["availability", "respect", "hours"]], ["I understand you, but it depends on making clear rules early. People usually respect clear availability."], "I see your point, but..."),
  T("Maybe. Although in a big company it's not that simple. Anyway, what do you do to relax? I've been trying to take up something that has nothing to do with screens, like painting or running.", "Quizás. Aunque en una empresa grande no es tan simple. ¿Qué haces tú para relajarte? Intento empezar algo sin pantallas, como pintar o correr."),
  C("What does the speaker want to find?", ["An activity without screens", "A new job", "A quieter office"], 0, "¿Qué quiere encontrar el hablante?"),
  Y("I usually go for a long walk or cook something elaborate. It helps me clear my head and stop thinking about work.", "Suelo dar un paseo largo o cocinar algo elaborado. Me ayuda a despejar la mente y dejar de pensar en el trabajo.", [["walk", "cook", "cooking"], ["clear my head", "relax", "help"], ["work", "thinking"]], ["Normally I take a long walk or make a complicated meal. It relaxes my mind so I don't think about work."], "I usually go for..."),
  T("Cooking is a great idea, actually. Maybe you could give me a recipe sometime. Well, this was a really interesting conversation. I should get back to work before my boss sends me an email!", "Cocinar es buena idea. Quizás me pases una receta. Fue una conversación interesante. ¡Debo volver al trabajo antes de que mi jefe me escriba!"),
  Y("Ha, of course. I'll send you a recipe this weekend. It was great talking to you, and don't work too late tonight!", "Claro. Te enviaré una receta este fin de semana. Fue un gusto hablar contigo, ¡y no trabajes hasta tarde hoy!", [["recipe", "send"], ["weekend", "this weekend"], ["talking", "great", "late"]], ["Sure, I will send you a recipe on the weekend. Nice talking to you, don't work late."], "I'll send you...")], minutes=10)

TALK("interview", "A job interview", "Responder preguntas de entrevista con ejemplos concretos", "B2.1", "daily", "Trabajo",
 "Hablar de tu experiencia, fortalezas, un desafío superado y hacer preguntas al entrevistador.",
 [["I have three years of experience in...", "Tengo tres años de experiencia en..."], ["One of my strengths is...", "Una de mis fortalezas es..."], ["I took the initiative to...", "Tomé la iniciativa de..."], ["As a result,...", "Como resultado,..."], ["Could you tell me more about the team?", "¿Podría contarme más sobre el equipo?"]],
 [T("Thanks for coming in today. To start, could you tell me a bit about yourself and your background?", "Gracias por venir hoy. Para empezar, ¿podría hablarme un poco de usted y su trayectoria?"),
  Y("Of course. I have three years of experience as a developer, mainly building web applications for small businesses.", "Claro. Tengo tres años de experiencia como desarrollador, principalmente creando aplicaciones web para pequeños negocios.", [["three years", "years", "experience"], ["developer", "web", "applications", "software"], ["small businesses", "businesses", "mainly"]], ["Sure. I've worked three years as a developer, mostly making web apps for small companies."], "I have three years..."),
  T("Interesting. What would you say is your biggest strength, and how has it helped you in your previous roles?", "Interesante. ¿Cuál diría que es su mayor fortaleza y cómo le ha ayudado en sus puestos anteriores?"),
  Y("One of my strengths is learning quickly. For example, I taught myself a new framework in a month, which allowed our team to launch on time.", "Una de mis fortalezas es aprender rápido. Por ejemplo, aprendí un framework nuevo en un mes, lo que permitió lanzar a tiempo.", [["strength", "learning", "learn quickly"], ["framework", "new", "month", "example"], ["launch", "on time", "team"]], ["I learn fast. For instance, I studied a new framework in one month and the team could launch on time."], "One of my strengths..."),
  T("That's impressive. Now, tell me about a time when something went wrong on a project. How did you handle it?", "Impresionante. Ahora cuénteme sobre una vez que algo salió mal en un proyecto. ¿Cómo lo manejó?"),
  C("What is the interviewer asking about?", ["A time something went wrong", "The salary expectations", "Plans for the future"], 0, "¿Sobre qué pregunta el entrevistador?"),
  Y("Last year, a deployment broke the payment system. I took the initiative to roll it back, and as a result we lost only twenty minutes of sales.", "El año pasado, un despliegue rompió el sistema de pagos. Tomé la iniciativa de revertirlo y, como resultado, solo perdimos veinte minutos de ventas.", [["deployment", "payment", "broke", "problem"], ["initiative", "roll back", "fixed", "solved"], ["result", "twenty minutes", "lost"]], ["Last year a release broke payments. I decided to undo it quickly, so we only lost twenty minutes of sales."], "Last year, a deployment..."),
  T("Good. Communication is essential here. How do you usually explain technical problems to people who aren't technical, like our sales team?", "Bien. La comunicación es esencial aquí. ¿Cómo explica normalmente los problemas técnicos a personas no técnicas, como nuestro equipo de ventas?"),
  Y("I try to avoid jargon and use simple analogies. I also focus on the impact on customers rather than the technical details.", "Intento evitar la jerga y usar analogías simples. También me centro en el impacto para los clientes más que en los detalles técnicos.", [["avoid", "jargon", "simple"], ["analogies", "examples", "explain"], ["impact", "customers", "focus"]], ["I use simple words and examples, not technical terms. I talk about what it means for the customers."], "I try to avoid jargon..."),
  T("That makes sense. Well, that's all from my side. Do you have any questions for us?", "Tiene sentido. Eso es todo de mi parte. ¿Tiene alguna pregunta para nosotros?"),
  Y("Yes, could you tell me more about the team I would be working with, and what a typical week looks like?", "Sí, ¿podría contarme más sobre el equipo con el que trabajaría y cómo es una semana típica?", [["tell me more", "could you", "team"], ["typical week", "week", "looks like"]], ["Yes, can you explain more about the team and what a normal week is like?"], "Could you tell me more..."),
  T("Of course. The team has six developers, and we do short daily meetings and a longer planning session every Monday. We'll be in touch by Friday. Thanks again for your time.", "Claro. El equipo tiene seis desarrolladores, con reuniones diarias cortas y una sesión de planificación los lunes. Le contactaremos antes del viernes. Gracias por su tiempo."),
  Y("Thank you for the opportunity. I look forward to hearing from you, and have a great day.", "Gracias por la oportunidad. Espero saber de ustedes. Que tengan un gran día.", [["thank", "opportunity"], ["look forward", "hearing"]], ["Thanks for the chance. I hope to hear from you soon. Have a nice day."], "I look forward to...")], minutes=10)

TALK("dev-standup", "The daily stand-up", "Contar tu avance, tus bloqueos y tus planes en una reunión diaria", "B1.2", "dev", "Desarrollo de software",
 "Usar tiempos verbales correctos para 'ayer / hoy / bloqueos' y pedir ayuda.",
 [["Yesterday I worked on...", "Ayer trabajé en..."], ["Today I'm going to...", "Hoy voy a..."], ["I'm blocked by...", "Estoy bloqueado por..."], ["Could you take a look at my pull request?", "¿Podrías revisar mi pull request?"], ["It should be done by Thursday.", "Debería estar listo el jueves."]],
 [T("Good morning, everyone. Let's start the stand-up. Luis, could you go first? What did you work on yesterday?", "Buenos días a todos. Empecemos el stand-up. Luis, ¿puedes empezar tú? ¿En qué trabajaste ayer?"),
  Y("Yesterday I worked on the login page. I fixed the validation error and I wrote two tests for it.", "Ayer trabajé en la página de login. Arreglé el error de validación y escribí dos pruebas.", [["yesterday", "worked"], ["login", "validation", "fixed"], ["tests", "wrote"]], ["Yesterday I was working on the login page. I fixed the validation bug and wrote two tests."], "Yesterday I worked on..."),
  T("Nice. And what's your plan for today? Remember that we have the release on Thursday, so we need to prioritise.", "Bien. ¿Y cuál es tu plan para hoy? Recuerda que el jueves es el lanzamiento, así que hay que priorizar."),
  Y("Today I'm going to connect the login page to the API and start on the password reset feature.", "Hoy voy a conectar la página de login a la API y empezar con la función de restablecer contraseña.", [["today", "going to"], ["api", "connect"], ["password reset", "password", "feature"]], ["Today I will connect the login page with the API and begin the password reset feature."], "Today I'm going to..."),
  T("Sounds good. Any blockers? Is there anything preventing you from moving forward?", "Suena bien. ¿Algún bloqueo? ¿Algo te impide avanzar?"),
  Y("Yes, I'm blocked by the staging server. It's been down since last night, so I can't test my changes.", "Sí, estoy bloqueado por el servidor de staging. Está caído desde anoche y no puedo probar mis cambios.", [["blocked", "problem", "issue"], ["staging", "server", "down"], ["test", "can't", "cannot"]], ["I have a blocker, the staging server has been down since last night and I cannot test."], "I'm blocked by..."),
  T("Right, thanks for flagging that. Priya, you set up that server, right? Could you look into it right after this meeting? It's affecting a couple of people.", "Gracias por avisarlo. Priya, tú configuraste ese servidor, ¿no? ¿Podrías revisarlo justo después de la reunión? Afecta a varias personas."),
  C("Who is asked to fix the staging server?", ["Luis", "Priya", "The manager"], 1, "¿A quién le piden arreglar el servidor?"),
  Y("Thanks, Priya. Also, could someone take a look at my pull request? It's a small change, but I'd like a second pair of eyes.", "Gracias, Priya. Además, ¿alguien podría revisar mi pull request? Es un cambio pequeño pero quisiera una segunda opinión.", [["thanks", "priya"], ["pull request", "take a look", "review"], ["second", "eyes", "opinion", "small"]], ["Thank you Priya. Can somebody review my pull request? It is small but I want another person to check it."], "Could someone take a look..."),
  T("I can do that after lunch. When do you think the password reset will be ready? I'd like to give the client an update.", "Yo puedo hacerlo después del almuerzo. ¿Cuándo crees que estará lista la función de contraseña? Quiero dar una actualización al cliente."),
  Y("It should be done by Wednesday afternoon, as long as the staging server is back up today.", "Debería estar lista el miércoles por la tarde, siempre que el servidor de staging vuelva hoy.", [["wednesday", "should be done", "ready"], ["as long as", "if", "server", "staging"]], ["It will be ready by Wednesday afternoon if the staging server works again today."], "It should be done by...")], dev=1, minutes=8)

TALK("dev-bug", "Explaining a bug to a teammate", "Describir un error, reproducirlo y proponer una solución", "B2.1", "dev", "Desarrollo de software",
 "Explicar qué pasa, cuándo pasa, qué has probado y qué propones hacer.",
 [["It only happens when...", "Solo pasa cuando..."], ["I managed to reproduce it.", "Logré reproducirlo."], ["The root cause seems to be...", "La causa raíz parece ser..."], ["I'd suggest we...", "Sugeriría que..."], ["In the meantime, we can...", "Mientras tanto, podemos..."]],
 [T("Hey Luis, thanks for jumping on a call. QA says the checkout page sometimes freezes on mobile. Have you been able to look into it?", "Hola Luis, gracias por unirte a la llamada. QA dice que la página de pago a veces se congela en móvil. ¿Has podido revisarlo?"),
  Y("Yes, I managed to reproduce it. It only happens when the user taps the pay button twice very quickly.", "Sí, logré reproducirlo. Solo pasa cuando el usuario toca el botón de pagar dos veces muy rápido.", [["reproduce", "managed"], ["only happens", "when", "twice"], ["pay button", "button", "taps"]], ["Yes, I could reproduce it. It happens only if the user presses the pay button twice fast."], "I managed to reproduce it..."),
  T("Interesting. So the second tap is causing something. Did you check the logs? Sometimes the error is hiding there, and it could be a network timeout rather than a frontend issue.", "Interesante. El segundo toque provoca algo. ¿Revisaste los logs? A veces el error está ahí y podría ser un timeout de red y no un problema del frontend."),
  Y("I did. The logs show two requests reaching the server at the same time, so the root cause seems to be a race condition.", "Sí. Los logs muestran dos peticiones llegando al servidor a la vez, así que la causa raíz parece ser una condición de carrera.", [["logs", "checked"], ["two requests", "same time", "requests"], ["root cause", "race condition", "cause"]], ["Yes. The logs show two requests arriving together, so the main cause looks like a race condition."], "The logs show..."),
  C("What is the root cause according to Luis?", ["A slow network", "A race condition from two requests", "A missing image"], 1, "¿Cuál es la causa según Luis?"),
  T("That makes sense. So what would you suggest? We can't ask users to tap only once, obviously, and we're releasing the new version on Friday.", "Tiene sentido. ¿Qué sugieres? No podemos pedirle a los usuarios que toquen una vez, y el viernes sale la nueva versión."),
  Y("I'd suggest we disable the button after the first tap and make the server ignore duplicate requests. That way we fix it on both sides.", "Sugeriría deshabilitar el botón tras el primer toque y hacer que el servidor ignore peticiones duplicadas. Así lo arreglamos en ambos lados.", [["suggest", "disable", "button"], ["server", "ignore", "duplicate"], ["both sides", "both", "way"]], ["I suggest we turn off the button after the first tap and let the server ignore duplicate requests, so both sides are protected."], "I'd suggest we..."),
  T("Solid plan. The server-side fix is important, because a client-side fix alone can always be bypassed. How long do you think it will take, including tests?", "Buen plan. El arreglo del servidor es importante, porque uno solo en el cliente puede saltarse. ¿Cuánto tardarías incluyendo pruebas?"),
  Y("I think about a day and a half, including tests. In the meantime, we can add a warning to the release notes.", "Creo que día y medio, incluyendo pruebas. Mientras tanto podemos añadir una advertencia en las notas de la versión.", [["day", "half", "time", "hours"], ["tests", "including"], ["in the meantime", "meantime", "release notes", "warning"]], ["Around a day and a half with tests. Meanwhile we could put a warning in the release notes."], "In the meantime..."),
  T("Perfect. Let's open a ticket and assign it to you. Thanks for the clear explanation, Luis. It made my job much easier.", "Perfecto. Abramos un ticket y te lo asigno. Gracias por la explicación clara, Luis. Me facilitó mucho el trabajo."),
  Y("No problem. I'll write the ticket right now, and I'll ping you when the pull request is ready for review.", "Sin problema. Escribo el ticket ahora mismo y te aviso cuando el pull request esté listo para revisión.", [["ticket", "write"], ["ping", "tell", "let you know", "message"], ["pull request", "ready", "review"]], ["No worries. I will create the ticket now and let you know when the pull request is ready to review."], "I'll write the ticket...")], dev=2, minutes=10)


TALK("hotel-mixup", "A booking problem at the hotel", "Resolver un problema de reserva y quejarte con cortesía", "B2.1", "daily", "Viajes",
 "Explicar un problema, pedir una solución concreta y negociar una compensación sin perder la calma.",
 [["I have a reservation under the name of...", "Tengo una reserva a nombre de..."], ["There seems to have been a mix-up.", "Parece que hubo una confusión."], ["I'd appreciate it if you could...", "Le agradecería que pudiera..."], ["Would it be possible to...?", "¿Sería posible...?"], ["I'm afraid that's not acceptable.", "Me temo que eso no es aceptable."]],
 [T("Good evening, and welcome to the Grand Harbour Hotel. May I have your name and a booking reference, please?", "Buenas noches y bienvenido al Grand Harbour Hotel. ¿Me da su nombre y la referencia de la reserva?"),
  Y("Good evening. I have a reservation under the name of Camargo for three nights, and the reference is on my confirmation email.", "Buenas noches. Tengo una reserva a nombre de Camargo por tres noches y la referencia está en mi correo de confirmación.", [["reservation", "booking"], ["camargo", "name"], ["three nights", "nights", "reference", "email"]], ["Good evening. There is a booking for Camargo for three nights and the reference is in my email."], "I have a reservation under..."),
  T("Thank you. Hmm, that's strange. I can see a booking for that name, but it's for next week, not tonight. And to make matters worse, we're fully booked this evening because of a conference in town.", "Gracias. Qué raro. Veo una reserva con ese nombre pero es para la próxima semana, no hoy. Y para colmo estamos llenos esta noche por una conferencia en la ciudad."),
  C("What is the problem with the reservation?", ["It is for the wrong week", "The room is too expensive", "The name is spelled wrong"], 0, "¿Cuál es el problema?"),
  Y("There seems to have been a mix-up, because I booked for tonight and I have the confirmation. I've been travelling for ten hours, so I really need a room.", "Parece que hubo una confusión, porque reservé para hoy y tengo la confirmación. He viajado diez horas, así que realmente necesito una habitación.", [["mix-up", "mistake", "confusion", "error"], ["booked", "tonight", "confirmation"], ["travelling", "ten hours", "need a room", "room"]], ["It looks like there was a mistake. I booked for tonight, I have the confirmation, and I have travelled for ten hours so I need a room."], "There seems to have been..."),
  T("I completely understand, and I apologise for the inconvenience. Let me check with my manager. One option is a room in our sister hotel, five minutes away by taxi. We would cover the transfer and give you a free breakfast tomorrow.", "Lo entiendo perfectamente y me disculpo por las molestias. Consultaré con mi gerente. Una opción es una habitación en nuestro hotel hermano, a cinco minutos en taxi. Cubriríamos el traslado y desayuno gratis mañana."),
  Y("That's a start, but I'd appreciate it if you could also cover the second night, since this mistake wasn't my fault.", "Es un comienzo, pero le agradecería que también cubriera la segunda noche, ya que este error no fue mi culpa.", [["appreciate", "would like", "could"], ["second night", "cover", "pay"], ["not my fault", "wasn't my fault", "mistake"]], ["That helps, but could you also pay for the second night? The mistake was not my fault."], "That's a start, but..."),
  T("I see your point. Normally we can't offer that, but given the circumstances, I think we can give you a fifty per cent discount on the second night. Would that be acceptable?", "Entiendo. Normalmente no podemos, pero dadas las circunstancias, podemos darle un cincuenta por ciento de descuento en la segunda noche. ¿Le parece aceptable?"),
  Y("Fifty per cent is fair, provided that the room has a proper desk, because I need to work tomorrow morning. Would it be possible to check that first?", "El cincuenta por ciento es justo, siempre que la habitación tenga un escritorio adecuado, porque tengo que trabajar mañana. ¿Sería posible comprobarlo primero?", [["fifty", "fair", "acceptable"], ["desk", "work"], ["possible", "check", "first"]], ["Fifty percent is reasonable as long as the room has a good desk, I have to work in the morning. Could you check it first?"], "Would it be possible to..."),
  T("Of course, I'll call them right now. Yes, they do have a desk and fast wifi. I'll book the taxi and send the details to your phone. Again, we're truly sorry about this.", "Claro, los llamo ahora. Sí, tienen escritorio y wifi rápido. Reservo el taxi y envío los datos a su teléfono. De nuevo, lo sentimos mucho."),
  C("What will the hotel do for the guest?", ["Offer a room elsewhere, a taxi and a discount", "Give him a refund and nothing else", "Ask him to come back next week"], 0, "¿Qué hará el hotel?"),
  Y("Thank you for handling this so professionally. I'll leave a positive review if everything goes smoothly tomorrow.", "Gracias por manejar esto tan profesionalmente. Dejaré una reseña positiva si todo sale bien mañana.", [["thank", "professionally", "handling"], ["review", "positive"], ["smoothly", "goes", "everything"]], ["Thanks for dealing with this so well. I will write a good review if everything goes well tomorrow."], "Thank you for handling...")], minutes=10)

TALK("restaurant-dinner", "Dinner with dietary needs", "Pedir, preguntar por ingredientes y resolver un problema en el restaurante", "B2.1", "daily", "Restaurantes",
 "Preguntar por ingredientes, expresar preferencias y necesidades, quejarte con tacto y pagar la cuenta.",
 [["What would you recommend?", "¿Qué me recomienda?"], ["Does this dish contain...?", "¿Este plato contiene...?"], ["I'm allergic to...", "Soy alérgico a..."], ["Could we have the bill, please?", "¿Nos trae la cuenta, por favor?"], ["I'm afraid this isn't what I ordered.", "Me temo que esto no es lo que pedí."]],
 [T("Good evening! Welcome to Olive & Ember. Can I start you off with something to drink, and have you had a chance to look at the menu?", "¡Buenas noches! Bienvenidos a Olive & Ember. ¿Empiezo con algo de beber? ¿Han podido mirar el menú?"),
  Y("Yes, thank you. Could we have a jug of water for the table, and I'd like a glass of red wine, whatever you recommend.", "Sí, gracias. ¿Podrían traernos una jarra de agua y yo quisiera una copa de vino tinto, lo que usted recomiende?", [["water", "jug"], ["red wine", "wine", "glass"], ["recommend", "whatever"]], ["Yes please. Can you bring a jug of water, and I would like a glass of red wine, you choose."], "Could we have..."),
  T("Certainly. Our house red is a Rioja from a small family vineyard, and it goes very well with the lamb. Are there any allergies or dietary requirements I should let the kitchen know about?", "Por supuesto. Nuestro tinto de la casa es un Rioja de una bodega familiar y va muy bien con el cordero. ¿Hay alergias o requisitos que deba informar a la cocina?"),
  Y("Yes, I'm allergic to nuts, and my friend is vegetarian. Does the mushroom risotto contain any nuts?", "Sí, soy alérgico a los frutos secos y mi amigo es vegetariano. ¿El risotto de champiñones contiene frutos secos?", [["allergic", "nuts"], ["vegetarian", "friend"], ["risotto", "contain", "mushroom"]], ["I have an allergy to nuts and my friend does not eat meat. Are there nuts in the mushroom risotto?"], "I'm allergic to nuts..."),
  T("Good question. The risotto itself is nut-free, but it's finished with a pesto that usually contains pine nuts. I can ask the chef to leave it out, and I'd recommend the grilled sea bass as well, which is naturally safe. The chef is very careful about cross-contamination.", "Buena pregunta. El risotto no tiene frutos secos, pero termina con un pesto que suele llevar piñones. Puedo pedir al chef que lo omita, y recomiendo la lubina a la parrilla, que es segura. El chef cuida la contaminación cruzada."),
  C("What does the waiter suggest about the risotto?", ["Ask the chef to leave out the pesto", "Add extra nuts", "Order a different starter"], 0, "¿Qué sugiere el camarero del risotto?"),
  Y("In that case, I'll have the sea bass, and my friend will have the risotto without the pesto. We'll share some vegetables as a side.", "En ese caso, yo pediré la lubina y mi amigo el risotto sin el pesto. Compartiremos unas verduras de acompañamiento.", [["sea bass", "fish", "bass"], ["risotto", "without", "pesto"], ["share", "vegetables", "side"]], ["Then I will take the sea bass and my friend the risotto with no pesto. We will share some vegetables."], "In that case..."),
  T("Wonderful. I'll bring those out shortly. ... Here you are, the sea bass and the risotto. Enjoy your meal! ... Is everything to your liking?", "Estupendo. Enseguida. ... Aquí tienen la lubina y el risotto. ¡Buen provecho! ... ¿Todo a su gusto?"),
  Y("Actually, I'm afraid the fish is a little overcooked, and it's not quite as warm as I expected. Would it be possible to have it replaced?", "En realidad, me temo que el pescado está un poco pasado y no está tan caliente como esperaba. ¿Sería posible cambiarlo?", [["afraid", "actually", "sorry"], ["overcooked", "cold", "warm", "fish"], ["replace", "replaced", "change", "possible"]], ["Actually the fish is a bit overdone and not hot enough. Could you change it please?"], "I'm afraid the fish..."),
  T("I'm so sorry about that, I'll take it back at once. The kitchen will prepare a fresh one, and dessert is on the house to make up for the wait.", "Lo siento mucho, me lo llevo enseguida. La cocina preparará uno nuevo y el postre va por cuenta de la casa por la espera."),
  Y("That's very kind of you, thank you. When we're ready, could we have the bill, and could we split it between the two of us?", "Es muy amable, gracias. Cuando estemos listos, ¿nos trae la cuenta y podemos dividirla entre los dos?", [["kind", "thank"], ["bill", "check"], ["split", "two", "between"]], ["Thank you, that is kind. Later can we get the bill and divide it between us two?"], "Could we have the bill...")], minutes=10)

TALK("social-media", "Social media, privacy and habits", "Debatir con un amigo sobre redes sociales, privacidad y tiempo en pantalla", "B2.1", "daily", "Redes sociales",
 "Describir hábitos, dar opiniones matizadas sobre privacidad e influencia, y proponer cambios.",
 [["I spend far too much time on...", "Paso demasiado tiempo en..."], ["It's a double-edged sword.", "Es un arma de doble filo."], ["I try not to take it too seriously.", "Intento no tomármelo demasiado en serio."], ["I've been meaning to cut down on...", "He querido reducir..."], ["It's a fine line between... and...", "Hay una línea muy fina entre... y..."]],
 [T("Did you see that my screen-time report says I spent six hours a day on my phone last week? Six! And most of it was scrolling through social media. I'm a bit embarrassed, to be honest.", "¿Viste que mi reporte de tiempo de pantalla dice que pasé seis horas al día en el teléfono la semana pasada? ¡Seis! Y casi todo fue desplazándome por redes sociales. Me da un poco de vergüenza."),
  Y("Honestly, I spend far too much time on it as well. It's hard not to, since the apps are designed to keep you hooked.", "Sinceramente, yo también paso demasiado tiempo. Es difícil no hacerlo porque las aplicaciones están diseñadas para engancharte.", [["too much time", "spend", "far too much"], ["hard", "difficult", "designed"], ["hooked", "apps", "keep"]], ["To be honest I also spend too much time on it. It is difficult because the apps are made to keep you hooked."], "I spend far too much time..."),
  T("Exactly. The algorithm knows exactly what to show you. And it's not just about time. I've started to feel worse about my own life after seeing everyone's holiday photos and promotions. Everybody seems so successful online.", "Exacto. El algoritmo sabe qué mostrarte. Y no es solo el tiempo. Me siento peor con mi vida al ver fotos de vacaciones y ascensos de todos. Todos parecen exitosos en línea."),
  C("How does the speaker feel after using social media?", ["Worse about their own life", "More motivated to work", "More informed about the news"], 0, "¿Cómo se siente el hablante?"),
  Y("I know what you mean, but I try not to take it too seriously. People only post their best moments, so it's a highlight reel, not real life.", "Sé a qué te refieres, pero intento no tomármelo demasiado en serio. La gente solo publica sus mejores momentos, así que es un resumen de lo mejor, no la vida real.", [["know what you mean", "understand", "i see"], ["not take it seriously", "seriously", "not real"], ["best moments", "highlight", "post"]], ["I understand, but I try not to take it very seriously. People post only their best moments, it is not real life."], "I try not to take it too seriously..."),
  T("That's a healthy way to look at it. What about privacy, though? Last month I discovered that an app I use had been sharing my location data with advertisers. I had no idea. Do you ever think about what they do with all that information?", "Es una forma sana de verlo. ¿Y la privacidad? El mes pasado descubrí que una app compartía mi ubicación con anunciantes. No tenía idea. ¿Piensas en qué hacen con esa información?"),
  Y("Increasingly, yes. I've turned off location tracking for most apps, and I check the privacy settings every few months. It's a bit of a hassle, though.", "Cada vez más. He desactivado la ubicación en la mayoría de apps y reviso la configuración de privacidad cada unos meses. Aunque es una lata.", [["turned off", "location", "tracking"], ["privacy", "settings", "check"], ["hassle", "bother", "effort"]], ["More and more, yes. I disabled location tracking on most apps and review the privacy settings every few months. It is annoying."], "I've turned off..."),
  T("Smart. I think the biggest issue is that these platforms are free because we're the product. Anyway, what about influencers? My cousin is convinced she can make a living from posting videos.", "Inteligente. El mayor problema es que son gratuitas porque nosotros somos el producto. ¿Y los influencers? Mi prima cree que puede vivir de subir videos."),
  Y("It's a double-edged sword. Some influencers earn a lot, but it's a fine line between authentic recommendations and paid advertising, and most followers can't tell the difference.", "Es un arma de doble filo. Algunos ganan mucho, pero hay una línea muy fina entre recomendaciones auténticas y publicidad pagada, y la mayoría no nota la diferencia.", [["double-edged", "risk", "both"], ["fine line", "authentic", "paid", "advertising"], ["followers", "difference", "tell"]], ["It has good and bad sides. Some earn well but it is hard to see the difference between real recommendations and paid ads, and followers cannot tell."], "It's a double-edged sword..."),
  T("True. Well, I've decided to try something. I'm going to delete the apps from my phone for a week and see how it feels. Would you like to join me?", "Cierto. He decidido probar algo: borrar las apps del teléfono una semana y ver cómo me siento. ¿Quieres unirte?"),
  Y("I've been meaning to cut down on my screen time, so why not? Let's check in with each other every couple of days to keep ourselves honest.", "He querido reducir mi tiempo de pantalla, así que ¿por qué no? Escribámonos cada un par de días para ser honestos.", [["cut down", "screen time", "reduce"], ["why not", "join", "let's"], ["check in", "every", "days", "honest"]], ["I have wanted to reduce my screen time so yes, let's do it. We can message every two days to be honest."], "I've been meaning to cut down...")], minutes=10)

TALK("new-laptop", "Choosing a new laptop", "Comparar dispositivos, preguntar especificaciones y decidir una compra", "B2.1", "daily", "Tecnología",
 "Preguntar por características técnicas, comparar opciones, negociar garantía y decidir con argumentos.",
 [["What are the specs like?", "¿Cómo son las especificaciones?"], ["How long does the battery last?", "¿Cuánto dura la batería?"], ["Is it worth the extra money?", "¿Vale el dinero extra?"], ["Does it come with a warranty?", "¿Viene con garantía?"], ["I'll go for the...", "Me quedaré con el..."]],
 [T("Hi there, are you finding everything alright? I noticed you've been looking at our laptops for a while. Can I help you narrow it down?", "Hola, ¿encuentra todo bien? Vi que lleva un rato mirando laptops. ¿Le ayudo a decidir?"),
  Y("Yes, please. I'm looking for a laptop for programming and some video calls, so I need something powerful but not too heavy.", "Sí, por favor. Busco una laptop para programar y videollamadas, así que necesito algo potente pero no muy pesado.", [["programming", "code", "work"], ["video calls", "calls"], ["powerful", "not too heavy", "light"]], ["Yes. I need a laptop to write code and make video calls, it should be powerful and light."], "I'm looking for a laptop..."),
  T("Understood. These two would suit you. This one has sixteen gigabytes of memory and a fast processor, but the battery lasts about eight hours. This other one is a bit more expensive, but the battery lasts up to fifteen hours and it weighs under a kilo and a half.", "Entendido. Estas dos le convienen. Esta tiene dieciséis gigas de memoria y un procesador rápido, pero la batería dura unas ocho horas. La otra es más cara, pero su batería dura hasta quince horas y pesa menos de un kilo y medio."),
  C("What is the main difference between the two laptops?", ["Battery life and weight", "The colour", "The screen size only"], 0, "¿Cuál es la principal diferencia?"),
  Y("How long does the battery actually last with normal use? Manufacturers usually exaggerate, so I'd rather hear a realistic number.", "¿Cuánto dura realmente la batería con uso normal? Los fabricantes suelen exagerar, así que prefiero un número realista.", [["how long", "battery", "last"], ["normal", "actually", "realistic", "real"], ["exaggerate", "manufacturers", "rather"]], ["What is the real battery life in normal use? Manufacturers often exaggerate so I prefer a realistic number."], "How long does the battery..."),
  T("Fair point. In real conditions, with a browser and a code editor open, you'd get around ten to eleven hours on the second one. The first would give you about five or six. If you work away from your desk a lot, that's a big difference.", "Buen punto. En condiciones reales, con navegador y editor de código, obtendría unas diez u once horas con la segunda y cinco o seis con la primera. Si trabaja mucho fuera del escritorio, es una gran diferencia."),
  Y("I often work in cafes, so the second one makes more sense. Is it worth the extra money, though? How much more is it?", "Trabajo a menudo en cafeterías, así que la segunda tiene más sentido. ¿Vale el dinero extra? ¿Cuánto más cuesta?", [["cafes", "work", "often"], ["second", "makes sense"], ["worth", "extra money", "how much"]], ["I often work in cafes so the second is better. Is the extra money worth it? What is the price difference?"], "Is it worth the extra money..."),
  T("It's three hundred euros more. But it comes with a three-year warranty instead of two, and I can include a protective case for free if you buy today.", "Son trescientos euros más. Pero incluye tres años de garantía en vez de dos y puedo añadir una funda gratis si compra hoy."),
  Y("A longer warranty is a strong selling point. Does it cover accidental damage, like spilling coffee on the keyboard, or only manufacturing faults?", "Una garantía más larga es un buen argumento. ¿Cubre daños accidentales, como derramar café en el teclado, o solo defectos de fábrica?", [["warranty", "cover"], ["accidental", "damage", "spilling", "coffee"], ["only", "manufacturing", "faults"]], ["A longer warranty is good. Does it cover accidents like coffee on the keyboard or only factory problems?"], "Does it cover accidental damage..."),
  T("Only manufacturing faults, I'm afraid. For accidents, you'd need our extended protection plan, which costs seventy euros a year.", "Solo defectos de fábrica, me temo. Para accidentes necesitaría nuestro plan de protección ampliada, que cuesta setenta euros al año."),
  Y("All things considered, I'll go for the lighter one with the longer battery, and I'll skip the protection plan. Could you include the case and a discount on a mouse?", "Considerando todo, me quedo con la más ligera y de batería larga, y omito el plan de protección. ¿Podría incluir la funda y un descuento en un ratón?", [["go for", "take", "buy", "lighter"], ["skip", "protection plan", "without"], ["case", "discount", "mouse"]], ["Overall I will take the light one with the long battery and not the protection plan. Can you add the case and a mouse discount?"], "I'll go for the...")], minutes=10)

TALK("flight-cancelled", "A cancelled flight", "Negociar con una aerolínea tras una cancelación y conocer tus derechos", "B2.2", "daily", "Viajes",
 "Exponer hechos con precisión, citar derechos, rechazar una oferta insuficiente y cerrar un acuerdo.",
 [["I was informed at the last minute that...", "Me informaron a última hora de que..."], ["Under the regulations, I'm entitled to...", "Según la normativa tengo derecho a..."], ["That doesn't quite cover...", "Eso no cubre del todo..."], ["I'd like that in writing.", "Quisiera eso por escrito."], ["In light of the circumstances,...", "Dadas las circunstancias,..."]],
 [T("Thank you for waiting, sir. I understand you're here regarding flight two-one-four to Madrid, which was cancelled this morning. I'm very sorry for the disruption. How can I assist you?", "Gracias por esperar. Entiendo que viene por el vuelo dos-uno-cuatro a Madrid, cancelado esta mañana. Lamento la interrupción. ¿En qué puedo ayudarle?"),
  Y("I was informed at the last minute that my flight was cancelled, and I have an important meeting tomorrow morning, so I need to be rebooked on the earliest possible flight.", "Me informaron a última hora de que mi vuelo se canceló y tengo una reunión importante mañana temprano, así que necesito que me reubiquen en el primer vuelo posible.", [["informed", "cancelled", "last minute"], ["meeting", "tomorrow", "important"], ["rebooked", "earliest", "flight"]], ["They told me at the last moment that my flight was cancelled and I have an important meeting in the morning, so I need the first possible flight."], "I was informed at the last minute..."),
  T("I completely understand. Unfortunately, the next direct flight with available seats is at noon tomorrow. There's an alternative through Lisbon this evening, but it involves a three-hour layover, and you'd arrive at midnight.", "Lo entiendo. Lamentablemente, el próximo vuelo directo con plazas sale mañana a mediodía. Hay una alternativa por Lisboa esta tarde, con tres horas de escala, llegando a medianoche."),
  C("What are the two options offered?", ["A noon flight tomorrow or a flight through Lisbon tonight", "A train or a bus", "A refund or a hotel only"], 0, "¿Cuáles son las dos opciones?"),
  Y("The Lisbon route works better for me, since I can't afford to miss the meeting. However, I'd like to know what compensation I'm entitled to under the regulations.", "La ruta por Lisboa me conviene más, porque no puedo faltar a la reunión. Sin embargo, quisiera saber qué compensación me corresponde según la normativa.", [["lisbon", "route", "better"], ["compensation", "entitled"], ["regulations", "rules", "meeting"]], ["I prefer the route through Lisbon because I cannot miss the meeting. But I want to know what compensation I have the right to under the rules."], "I'd like to know what compensation..."),
  T("Of course. Since the cancellation was due to a technical fault, and you were notified less than fourteen days before departure, you're entitled to compensation. In this case, that would be two hundred and fifty euros, plus meals and refreshments during the wait.", "Por supuesto. Como la cancelación fue por un fallo técnico y le avisaron con menos de catorce días, tiene derecho a compensación: doscientos cincuenta euros, más comidas y refrigerios durante la espera."),
  Y("That's helpful, but it doesn't quite cover the cost of the taxi I had booked and the hotel I have already paid for in Madrid tonight. Could those expenses be reimbursed as well?", "Es útil, pero no cubre del todo el taxi que había reservado ni el hotel que ya pagué en Madrid esta noche. ¿Podrían reembolsarse esos gastos?", [["doesn't cover", "not cover", "quite"], ["taxi", "hotel", "paid"], ["reimbursed", "expenses", "refund"]], ["It helps, but it does not fully cover the taxi and the hotel I paid for tonight in Madrid. Can you refund those expenses too?"], "That doesn't quite cover..."),
  T("If you can provide receipts, we can process a claim for reasonable expenses. I can't promise the full amount, but hotel cancellations are normally reimbursed. I'll need photos of the receipts sent to our customer service email.", "Si presenta recibos, podemos tramitar un reclamo por gastos razonables. No puedo prometer el monto completo, pero las cancelaciones de hotel suelen reembolsarse. Necesito fotos de los recibos enviadas a nuestro correo de atención."),
  Y("I'll send the receipts today. In the meantime, I'd like that in writing, both the compensation and the promise to review my expenses, so there's no misunderstanding later.", "Enviaré los recibos hoy. Mientras tanto, quisiera eso por escrito, tanto la compensación como el compromiso de revisar mis gastos, para que no haya malentendidos.", [["receipts", "send"], ["in writing", "writing", "email"], ["compensation", "expenses", "misunderstanding"]], ["I will send the receipts today. Meanwhile please put it in writing, the compensation and the promise to review my expenses, to avoid misunderstandings."], "I'd like that in writing..."),
  T("Absolutely. I'll email you a written confirmation within the hour, and I've also upgraded your seat on the Lisbon flight, free of charge, as a gesture of goodwill. Your boarding pass will be ready at gate twelve.", "Por supuesto. Le enviaré confirmación por escrito en menos de una hora, y he mejorado su asiento en el vuelo a Lisboa sin costo como gesto de buena voluntad. Su tarjeta de embarque estará en la puerta doce."),
  Y("In light of the circumstances, I appreciate the gesture. Thank you for your help, and I'll be waiting for that email.", "Dadas las circunstancias, aprecio el gesto. Gracias por su ayuda y esperaré ese correo.", [["appreciate", "thank"], ["email", "waiting", "written"], ["circumstances", "gesture", "help"]], ["Considering the situation I appreciate it. Thanks for helping me, I am waiting for the email."], "In light of the circumstances...")], minutes=10)

TALK("ai-at-work", "AI tools at work: a debate", "Debatir ventajas, riesgos y ética de la inteligencia artificial en el trabajo", "B2.2", "daily", "Tecnología",
 "Argumentar a favor y en contra, conceder puntos, matizar y llegar a una postura razonada.",
 [["There's no denying that...", "No se puede negar que..."], ["On the other hand,...", "Por otro lado,..."], ["What worries me is...", "Lo que me preocupa es..."], ["I'd argue that...", "Yo diría que..."], ["We should weigh the benefits against the risks.", "Deberíamos sopesar los beneficios frente a los riesgos."]],
 [T("So, our company has just announced that everyone will get access to an AI assistant for writing emails, summarising documents, even drafting reports. What's your take on it? Personally, I'm torn between excitement and suspicion.", "Nuestra empresa acaba de anunciar que todos tendrán un asistente de IA para redactar correos, resumir documentos e incluso redactar informes. ¿Qué opinas? Yo estoy dividido entre la emoción y la sospecha."),
  Y("There's no denying that it can save a lot of time. I've used it to summarise long documents, and it does that in seconds.", "No se puede negar que puede ahorrar mucho tiempo. Lo he usado para resumir documentos largos y lo hace en segundos.", [["no denying", "true", "time"], ["save", "saves", "time"], ["summarise", "documents", "seconds"]], ["It is true that it saves a lot of time. I have used it to summarize long documents and it takes seconds."], "There's no denying that..."),
  T("Right, but here's what worries me. Once you rely on it, do you still check the results carefully? I read that these systems sometimes state false information with total confidence, and busy people don't always double-check.", "Pero esto es lo que me preocupa. Una vez que dependes, ¿revisas los resultados con cuidado? Leí que estos sistemas a veces dicen datos falsos con total seguridad y la gente ocupada no siempre verifica."),
  C("What is the speaker worried about?", ["People not checking incorrect answers", "The tool being too slow", "The tool costing too much"], 0, "¿Qué preocupa al hablante?"),
  Y("That's a fair concern, and I'd argue the answer is training. Employees should treat the output as a first draft and always verify facts before sending anything.", "Es una preocupación válida y yo diría que la respuesta es la formación. Los empleados deben tratar el resultado como un primer borrador y verificar los datos antes de enviar.", [["fair", "concern", "worry"], ["training", "train"], ["draft", "verify", "check"]], ["That is a reasonable worry and I think the solution is training. People should see the result as a first draft and check the facts before sending."], "That's a fair concern..."),
  T("Sensible. And what about jobs? Some colleagues in the translation department are quite anxious. They think the company will eventually replace them, and after all, the first thing a business looks at is cost.", "Sensato. ¿Y los empleos? Algunos colegas del departamento de traducción están ansiosos. Creen que la empresa acabará reemplazándolos y, después de todo, lo primero que mira una empresa es el costo."),
  Y("On the other hand, history suggests that technology tends to change jobs rather than eliminate them. Translators could focus on quality control and more creative work, provided the company invests in retraining.", "Por otro lado, la historia sugiere que la tecnología tiende a cambiar los empleos y no a eliminarlos. Los traductores podrían centrarse en el control de calidad y en trabajo más creativo, siempre que la empresa invierta en reciclaje.", [["on the other hand", "history", "change"], ["quality", "creative", "focus", "translators"], ["retraining", "invest", "provided"]], ["However, technology usually changes jobs, it does not remove them. Translators could do quality control and creative work if the company pays for retraining."], "On the other hand..."),
  T("That's optimistic, but I'd like to believe it. There's also the question of privacy. If I paste a confidential contract into an AI tool, where does that data go? Nobody in management has answered that yet.", "Es optimista, pero quiero creerlo. También está la privacidad. Si pego un contrato confidencial en una herramienta de IA, ¿adónde van esos datos? Nadie en la gerencia lo ha respondido."),
  Y("That's the crucial question. Before anyone uses it with sensitive information, we should demand a clear policy on data storage, and use only versions that are approved by our security team.", "Esa es la pregunta crucial. Antes de usarla con información sensible, deberíamos exigir una política clara de almacenamiento de datos y usar solo versiones aprobadas por el equipo de seguridad.", [["crucial", "question", "important"], ["policy", "data", "storage", "clear"], ["approved", "security", "sensitive"]], ["That is the key question. Before using sensitive information we must ask for a clear policy on data storage and use only versions approved by security."], "That's the crucial question..."),
  T("Agreed. So where do you land? Is it worth adopting, on balance?", "De acuerdo. Entonces, ¿dónde te posicionas? ¿Vale la pena adoptarla, en conjunto?"),
  Y("On balance, yes, but we should weigh the benefits against the risks, start with a small pilot, and review the results after three months before rolling it out to everyone.", "En conjunto, sí, pero deberíamos sopesar beneficios frente a riesgos, empezar con un piloto pequeño y revisar los resultados a los tres meses antes de extenderlo a todos.", [["on balance", "yes", "worth"], ["weigh", "benefits", "risks"], ["pilot", "three months", "review"]], ["Overall yes, but compare benefits and risks, begin with a small pilot and check results after three months before giving it to everyone."], "On balance, yes...")], minutes=11)

os.makedirs(OUT, exist_ok=True)
for f in os.listdir(OUT):
    if f.endswith(".json"): os.remove(os.path.join(OUT, f))
idx = []
for t in TALKS:
    assert re.fullmatch(r"[\w-]+", t["id"])
    json.dump(t, open(os.path.join(OUT, t["id"] + ".json"), "w", encoding="utf-8"), ensure_ascii=False, separators=(",", ":"))
    idx.append({k: t[k] for k in ("id", "title", "es", "level", "track", "topic", "minutes") if k in t} | ({"dev": t["dev"]} if "dev" in t else {}) | {"turns": sum(1 for x in t["turns"] if "y" in x)})
json.dump(idx, open(os.path.join(OUT, "index.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print(len(TALKS), "conversaciones ->", OUT)
